# CUSTOM VALIDATOR
#validator: /home/dapregi/dev/argus/opencga_validator.py

# AUTHENTICATION INFO
authentication:
  ##  token: ssasasdsadsadasd.sdasd.asdasd
  ##  token: env(OPENCGA_TOKEN)
  token: login(response[0].result[0].token)
  url: http://bioinfo.hpc.cam.ac.uk/opencga-demo/webservices/rest/v1/users/demo/login
  headers:
    Accept-Encoding: gzip
  method: POST
  body: {"user": "demouser", "password": "demouser"}

# DEFAULT REST PARAMETERS
#rest:
#  headers:
#    Accept-Encoding: gzip
#  queryParams:
#    limit: 10
#    count: False

# SELECTED SUITES FOR TESTING
#suites:
# - variant

# TEST SELECTION
#tests:
#  ignore_async: false
#  ignore_method: ["POST"]
#  ignore_tag: ["SLOW"]

# VALIDATION PARAMETERS
validation:

  timeDeviation: 100  # % of time allowed to deviate from expected time (0-100)
  asyncRetryTime: 10  # retry time for checking asynchronous jobs

  ignore_time: false
  ignore_headers: []      ## example:  ["Content-Type"]
  ignore_results: []

  fail_on_first: False
