# CUSTOM VALIDATOR
validator: /path/to/opencga_validator.py

# WORKING DIR FOR CUSTOM INPUT/OUTPUT FILES
workingDir: /path/to/argus_working_dir

# BASE URL
baseUrl: https://example.com/webservices/rest/v2

# GLOBAL VARIABLES
variables:
  varName: varValue

# AUTHENTICATION INFO
#authentication:
#  # token: ssasasdsadsadasd.sdasd.asdasd
#  # token: env(OPENCGA_TOKEN)
#  token: login(responses[0].results[0].token)
#  url: https://example.com/webservices/rest/v2/users/login
#  headers:
#    Accept-Encoding: gzip
#  method: POST
#  bodyParams: {"user": "USER", "password": "PASS"}

# DEFAULT PARAMETERS
#headers:
#  Accept-Encoding: gzip
#queryParams:
#  limit: 10
#  count: False

# SELECTED SUITES FOR TESTING
suites:
  - cohort

# TEST SELECTION
#tests:
#  ignore_async: false
#  ignore_method: ["POST"]
#  ignore_tag: ["SLOW"]

# VALIDATION PARAMETERS
validation:

  timeDeviation: 5  # +/- seconds allowed to deviate from expected time
  asyncRetryTime: 60  # retry time for checking asynchronous jobs

  ignoreTime: false  # ignore validation of response time
  ignoreHeaders: []  # ignore validation of header parameters (e.g. ["Content-Type"])
  ignoreResults: []  # ignore validation of particular methods (e.g. ["match", "list_contains"])

  failOnFirst: False  # stop validation in first FAIL
