# CUSTOM VALIDATOR
validator: /home/dapregi/dev/argus/opencga_validator.py

# BASE URL
baseUrl: https://test.app.zettagenomics.com/xeta-14s/opencga/webservices/rest/v2

# AUTHENTICATION INFO
#authentication:
#  # token: ssasasdsadsadasd.sdasd.asdasd
#  # token: env(OPENCGA_TOKEN)
#  token: login(responses[0].results[0].token)
#  url: https://test.app.zettagenomics.com/xeta-19e/opencga/webservices/rest/v2/users/login
#  headers:
#    Accept-Encoding: gzip
#  method: POST
#  body: {"user": "USER", "password": "PASS"}

# DEFAULT REST PARAMETERS
#rest:
#  headers:
#    Accept-Encoding: gzip
#  queryParams:
#    limit: 10
#    count: False

# SELECTED SUITES FOR TESTING
suites:
  - gene

# TEST SELECTION
#tests:
#  ignore_async: false
#  ignore_method: ["POST"]
#  ignore_tag: ["SLOW"]

# VALIDATION PARAMETERS
validation:

  timeDeviation: 100  # % of time allowed to deviate from expected time (0-100)
  asyncRetryTime: 10  # retry time for checking asynchronous jobs

  ignore_time: false
  ignore_headers: []      ## example:  ["Content-Type"]
  ignore_results: []

  fail_on_first: False
