# % of time allowed to deviate from expected time (0-100)


validator: opencga_validator

authentication:
#  token: ssasasdsadsadasd.sdasd.asdasd
#  token: env(OPENCGA_TOKEN)
  token: login(response[0].result[0].token)
  url: http://bioinfo.hpc.cam.ac.uk/opencga-demo/webservices/rest/v1/users/demo/login
#  headers:
#    Accept-Encoding: gzip
  method: POST
#  queryParams:
  body: {password: demo}

rest:
#  timeout: 30
  headers:
    Accept-Encoding: gzip
  queryParams:
    limit: 10
    count: False

suites:
 - projects
 - clinical

tests:
  ignore_async: false
  ignore_method: ["POST"]
  ignore_tag: ["SLOW"]

validation:

  timeDeviation: 100
  asyncRetryTime: 10

  ignore_time: False
  ignore_headers: []      ## example:  ["Content-Type"]
  ignore_fields: [""]

  fail_on_first: False
