# Custom validator
validator: /home/dapregi/dev/argus/opencga_validator.py

# Authentication info
authentication:
#  token: ssasasdsadsadasd.sdasd.asdasd
#  token: env(OPENCGA_TOKEN)
  token: login(response[0].result[0].token)
  url: http://bioinfo.hpc.cam.ac.uk/opencga-demo/webservices/rest/v1/users/demo/login
  headers:
    Accept-Encoding: gzip
  method: POST
#  queryParams:
  body: {password: demo}

# Default rest parameters
rest:
  headers:
    Accept-Encoding: gzip
  queryParams:
    limit: 10
    count: False

# Selected suites for testing
suites:
 - projects
 - variant

# Test selection
tests:
  ignore_async: false
  ignore_method: ["POST"]
  ignore_tag: ["SLOW"]

# Validation parameters
validation:

  timeDeviation: 100  # % of time allowed to deviate from expected time (0-100)
  asyncRetryTime: 10  # retry time for checking asynchronous jobs

  ignore_time: false
  ignore_headers: []      ## example:  ["Content-Type"]
  ignore_results: []

  fail_on_first: False
